# Aalto Pro/Diploma in Artificial Intelligence: Project work

## Applying data science and machine learning in development of a tool for sustainable waste management onboard cruise ship

### Abstract


### Background

In this work, a data product will be produced by using data science tools and machine learning (ML) algorithms that would help a cruise ship operator to plan ahead the future waste management operations by a most sustainable and feasible way.
The project work is done by constructing the ML-product by using real shipboard operational data and external web sources. The purpose is to create ML-system that would give a decent picture and prediction of the best option for the operations.

#### Cruise ship waste

A cruise ship is a passenger ship used for pleasure voyages when the voyage itself, the ship's amenities, and sometimes the different destinations along the way (i.e., ports of call), form part of the passengers' experience [1]. Modern cruise ships can be considered as a combination of hotel, shopping center, amusement park, casino, spa and a center of all kind of restaurants with big galleys for preparation of all kind of meals. All these onboard activities produces high volumes of wastes that is around 2 to 3 times the amount produced by municipal centers per capita [2]. Especially, as all the meals (around 8 per each day) are prepared onboard the ship in the central galleys. Thereby, organic and nutrient loading of the waste, if discharged to the sea, is very high.

The waste management system of a modern cruise ship is confined to ship machinery spaces. There are basically three type of solid waste produced onboard: Dry waste (DW), food waste (FW) and biosludge waste(BW). The DW is mainly solid packing materials from the provisions and unsorted waste from the cabins and restaurants. The FW is produced mainly from the food preparation from the gallies but also as a food rejects from bars, restaurants and crew messes of the ship. The BW is a biological surplus sludge from the ship wastewater treatment plant.

The management and the discharge of the waste materials is strictly regulated by both international and national legislations and guidelines. International Maritime Organisation (IMO) [3] The discharge of garbage is strictly prohibited in all sea areas. The discharge of FW and BW is also strictly regulated and also prohibited in many special sea areas. In addition to this the storage silos for these waste materials is very limited and is sufficient only for couple of days.

#### Motivation for the work

Evac Oy supplies integrated cleantech solutions, including e.g. waste management systems, to all types of ships. The cruise ships are our biggest market segment and for past few years Evac has had more than 80 % of market share in waste systems. The sustainability is the key value for all major cruise ship owners. Not only because of regulations and guidelines, but because of acceptability of the cruise business as a whole. Basically, the cruise ships are operated by zero-discharge principle.

The cruise ships are operated on a strictly defined itinerary and and in the given schedule. The shipboard waste management is not the main operation of the ship and should by not means affect the operation of a ship. On the other hand, volumetric production of the waste streams (DW, FW, BW) are not constant and are fairly unpredictable. As mentioned the onboard storage silos are very small in volume. For that reason, cruise ships are many times forced to store waste container in corridors and luggage storages. For the same reason, ships are frequently discharging high proportion of untreated FW and BW directly into the sea. This poses high risk for the reputation of the ship owners as well as for the whole cruise business.

### Purpose and objective

The purpose of this work is to carry out an exploratory analysis on the waste data produced from one of the ships of TUI Cruises to produce an insight of the dynamics of the waste production. From that knowledge a machine learning tool is trained and validated to predict the production of the waste streams. Ultimately, the project should produce a machine learning tool that will predict the production of the three streams and thereby help the operator to plan ahead the waste management operations of the ship.

The goal is to study how to extract usable data from the existing sources, clean and explore the data so that a usable predictive ML models could be produced and trained with new and fresh data in the future from the IoT-system. When this goal is achieved, it may be worth of considering to apply and further develop the extent of the work to an usable data science product.


## Materials and methods


### Data sources

#### Shipboard data

There are both internal and external data sources that would be used. The internal data sources are the waste data produced from the ship IoT. In the first stage of data exploration, a set of readily produced CSV-files containing all the waste data from Mein Schiff 6 covering couple of days. The raw data set consists of:

- volume as cubic meters (m3) of dry waste produced onboard cruise ship into a dry waste silo. The CSV file contains status information of the gate valves that needs to be converted into a volumetric values of waste production. This data is converted to kilograms (kg) of dry waste and eventually rate of production.

- volume as cubic meters (m3) of food waste produced continuously onboard cruise ship into a food waste silo. There are two FW silos. The data is produced as filling %-level of the tanks. The data is converted into cumulative production of kilograms (kg) of food waste and eventually as rate of production

- volume as cubic meters (m3) of biosludge produced continuously onboard cruise ship into a BW silo. The data is produced as filling %-level of the tanks. The data is converted into cumulative production of kilograms (kg) of BW and eventually as rate of production.

In addition to the waste data, there is data of the waste management system including pumping information of the FW solids and liquid and data from waste incinerator units.

The first set of data is produced from Mein Schiff 6. As said, the data of the waste production is first cleaned and plotted to understand the nature of the data. These data sets will be used as labeled data for prediction of future waste production trends. The first development and training of the ML-model is done with this data set.


#### Operational data

For predicting the future waste production, we need to understand the basic facts and activities affecting the waste production rate in order to select sensible and most influential features for our ML-model. First one need to ask that is the ML-model really needed to know the future waste production. Basically, the prediction model would not be needed if the the production rate is either constant or the pattern of production rate is well known.

Is the production rate constant and/or is the production pattern know? To answer that question one need to know the variables affecting the waste production. The pattern of production is dependant mainly on:

- Activity of passangers that is dependant on the time of a day: That would basically be solved with Pandas datetime-data type.

- Amount of passangers onboard: Basically, it is safe to assume that the ship is always fully booked, that is the situation almost always for all cruise ships in real life. This may be thereby either neglected or use constant integer, i.e. known capacity of the ship derived from the web site of the ship by web scraping.

- Proportion of passangers present onboard: Cruise ships visit the ports on a daily basis and most of the cruise ship customers disembark to the port of call. So, the relevant question affecting the waste production; is the ship in a port side or cruising in the sea conditions? This information can be derived from the web site of the ship by web scraping. The data type is boolean.

- The amount of food waste is dependant on the meal time, meaning that two hours before and until the meal time the main galleys are fully operational. We can assume the meal times of a day based on our knowledge about the ship operation. The data type is boolean.

- During staying in the turnaround port (i.e. home port). The waste production is higher because the whole ship is cleaned between 8:00 am and 01:00 pm. This increases substantially the amount of DW.This information can be derived from the web site of the ship by web scraping. The data type is boolean.

As we can see, there is at least five most relevant attributes affecting the waste production rates. Thereby, one can safely conclude that the production rates aren't constant nor known. We can also conclude that the rates are not same throughout one day. Most likely the the production patterns are very ship-specific and cannot be generalised from single attribute. Therefore, the development of the predictive machine learning model is a relevant task.


### Method for development of Predictive Machine Learning model


Typical situation for creating a predictive model is that in a set of inputs (X) are readily available, but the output (Y) cannot be easily obtained [4]. The output can be predicted with an estimate of function describing the unknown relationship between X and Y. Basically, a model, that is an estimate of the relationship, is at first treated as a black box that would be called as hypothesis space, meaning all computationally reasonable relationships between X and Y.


#### Definition of the setup for the machine learning task


In this project, the high-level insight produced by the model is the production of the waste streams, DW, FW and BW, that will tell whether or not the storage capacities are sufficient. This will return recommendation of actions whether to treat the waste onboard, store in the silos or if the waste needs to be discharged to the sea. As an ultimate goal would be to combine the return value of sustainability in terms of environmental impact or feasibility information in terms of cash flow or cost from waste disposal.

The inputs (X) as relevant features for the ML-model are the operational data described above. The labelled data as relevant higher-level insights are the known shipboard data described above. This data will be supplemented by additional data from the IoT-system onboard Mein Schiff 2, that will be live after 11th April 2019. This data will be also used for furter training of the model as well as for the validation of the model.

The output (Y) predictions will be the predicted waste productions.


#### Development of the ML-model


The relevant question for development of the model is that is it possible to predict the waste production from the operational data listed above. The main prerequisite for development and training of predictive regression model is a feature space that is quantitative. However, as we can see our given feature space contains mainly categorical features with a boolean values.

In this case, one proven technique is to use one-hot encoding, which effectively creates extra columns indicating the presence or absence of a category with a value of 1 or 0, respectively [5]. In this project that would simply mean, e.g. ships location is indicated as one category a sea condition as 1 (True) and portside as 0 (False). Also, the meal time is one category indicated as either 1 (True) and rest of the time as 0 (False).

After preprosessing the features into useable feature space, the model is developed. The labelled data is joined with the another dataset. Basically, try to determine the extent to which the above listed operational data affect the volume of waste streams. A simple linear regression is performed to relate the operations and the labeled data.

The linear regression functionality of the Scikit-Learn-package will be utilised for model development and training the model as well as for the validation of the model


### Computational infrastructure, software product considerations

The work is done with Jupyter Lab of Anaconda distribution package. The code will be written in Python meaning that all the usable Python libraries, incl. Pandas for data preparation, Matplotlib and Seaborn for visualisation of cleaned data and Scikit-Learn for model training and validation.

The model development is the main goal of the project. As I have only basic level of programming knowledge, there is no guarantees that the work will be finalized as data product to be utilised by end-customer. The primary goal of the work is to learn the methods of data science and machine learning. If I get to the production stage with this work, the GUI would be developed PyQt-GUI-tool. Alternatively, a web application could be developed with Python Flask-package. As there is lot of real time data available, it would be preferable to have it running real time. For the employer company point of view, a software product would be the desired option. However, most of the efforts during these studies should be put to data management and the ML-model building. As long as there is no connection between a specific ship or the ship owner, there should not be any privacy issues. The model should basically be a tool for evaluating sustainability of human actions towards the nature. 


## Preliminary Conclusions 

Preliminary, it can be concluded that the data from the ship IoT-system is both dense and thereby noisy. The data sampling interval on 3 to 5 seconds is emphasising the underlying noise caused mainly by ship movement. Also, the data is derived mainly only as status information that causes multi-stage data transformation before one can make any meaningful visualisation of the data.

Deriving the operational data by web scraping is a good rehearsal for practice of data hacking from the website. However, the reliability of the data is dependant on whether or not the data on the webpage is correct or not. This entails a risk for model development stage.

The feature space contains mainly categorical data and needs preprocessing prior to model development. Also, it remains to be seen if this categorical feature space is applicable for training a reliable model.


##  References:

[1] https://en.wikipedia.org/wiki/Cruise_ship

[2] Cruise ship waste management database. Evac Oy. 2019.

[3] IMO Marpol Annex V, Resolution MEPC. 295(71).
    http://www.imo.org/en/OurWork/Environment/PollutionPrevention/Garbage/Pages/Default.aspx

[4] An Introduction to Statistical Learning with Applications in R. Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani. 2017. eBook. Corrected at 8th printing.

[5] Python Data Science Handbook. Essential Tools For Working With Data. Jake VanderPlas. 2017. 1st Edition. O'Reilly.

## APPENDIX 1: Code of the project. Status 1st of April 2019

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

or:

In [ ]:
%matplotlib inline

In [236]:
def LoadData(filename):# FILENAME ON INPUT-PARAMETRINÄ LOADDATA-FUNKTIOLLE. FILENAME ANNETAAN SIIS FUNKTIOTA KÄYTETTÄESSÄ.
    """
    Load the csv reading the file with the filename given as a parameter.
    Print the sample size m and the feature length n.

    :input: String path to the file

    :return: pandas dataframe of shape=(m, n, ty), the sample size m and the feature length n 
    and the data type ty. In this case no conversion to Numpy array    
    """

    df = pd.read_csv(filename, delimiter=';')
    #X = df.values # convert the data frame to numpy array
    n = df.shape[1]        # second element of "dimension" is the number of cols
    m = df.shape[0]        # first element of dimension is the number of rows
    ty = type(df)
    print('sample size m=',m)
    print('feature length n=',n)
    print('the data type is', ty)
    return df, m, n, ty

In [237]:
FWAsource, m, n, ty, = LoadData('MS6/LEVEL_TANK_A0.csv')

sample size m= 402860
feature length n= 5
the data type is <class 'pandas.core.frame.DataFrame'>

In [239]:
FWAsource.head()

,VarName,TimeString,VarValue,Validity,Time_ms
0,FOODWASTE_TANK_A_LEVEL_TREND,25.02.2018 16:07:23,47,1,"43156671788,5185"
1,HARSLEV_PUMP_1_1PM_1_STATUS,25.02.2018 16:07:25,20,1,"43156671811,9097"
2,THREEWAY_VALVE_1_1PV4_STATUS,25.02.2018 16:07:25,5,1,"43156671811,9097"
3,HARSLEV_PUMP_1_1PM_1_STATUS,25.02.2018 16:07:27,20,1,"43156671835,2894"
4,THREEWAY_VALVE_1_1PV4_STATUS,25.02.2018 16:07:27,5,1,"43156671835,2894"

In [240]:
def LoadDatac(filename):
    """
    Load the csv reading the file with the filename given as a parameter.
    Print the sample size m and the feature length n.

    :input: String path to the file

    :return: pandas dataframe of shape=(m, n, ty), the sample size m and the feature length n 
    and the data type ty. In this case no conversion to Numpy array    
    """

    df = pd.read_csv(filename, delimiter=',')
    #X = df.values # convert the data frame to numpy array
    n = df.shape[1]        # second element of "dimension" is the number of cols
    m = df.shape[0]        # first element of dimension is the number of rows
    ty = type(df)
    print('sample size m=',m)
    print('feature length n=',n)
    print('the data type is', ty)
    return df, m, n, ty

In [ ]:
FWBsource, m, n, ty, = LoadData('MS6/LEVEL_TANK_B0.csv')

In [ ]:
BWsource, m, n, ty, = LoadData('MS6/LEVEL_BIOSLUDGETANK0.csv')

In [ ]:
DWsource, m, n, ty, = LoadData('MS6/Inc_1_datalog_functions0.csv')

In [ ]:
DWsource.head()

In [ ]:
def Datetime(df):# PANDAS DF ON INPUT-PARAMETRINÄ FUNKTIOLLE. DF:N NIMI ANNETAAN SIIS FUNKTIOTA KÄYTETTÄESSÄ.
    """
    Converts the str-type TimeString into more useful Pandas DateTime form.
    
    Prints the head of the DataFrame after conversion and the data type of the DateTime column.

    :input: Name of the dataframe and the TimeString column of the DF in question.

    :return: pandas dataframe with the DateTime and its data type.    
    """

    df['DateTime'] = pd.to_datetime(df.TimeString, format = '%d.%m.%Y %H:%M:%S')
    dty = type(df.DateTime)    # Returns datatype
    print(df.head())
    print('The time data type is now: ',dty)
    return df, dty

In [ ]:
Datetime(DWsource)

In [199]:
DWsource.head(10)

,VarName,TimeString,VarValue,Validity,Time_ms,DateTime
0,inc_1_primary_burner_status,17.02.2018 21:03:15,0,1,"43148877259,4097",2018-02-17 21:03:15
1,inc_1_secondary_burner_status,17.02.2018 21:03:15,-20,1,"43148877259,4097",2018-02-17 21:03:15
2,inc_1_lower_feeding_gate_status,17.02.2018 21:03:15,-10,1,"43148877259,4097",2018-02-17 21:03:15
3,inc_1_medical_flap_status,17.02.2018 21:03:15,-5,1,"43148877259,4097",2018-02-17 21:03:15
4,inc_1_primary_burner_status,17.02.2018 21:03:16,0,1,"43148877271,0995",2018-02-17 21:03:16
5,inc_1_secondary_burner_status,17.02.2018 21:03:16,-20,1,"43148877271,0995",2018-02-17 21:03:16
6,inc_1_lower_feeding_gate_status,17.02.2018 21:03:16,-10,1,"43148877271,0995",2018-02-17 21:03:16
7,inc_1_medical_flap_status,17.02.2018 21:03:16,-5,1,"43148877271,0995",2018-02-17 21:03:16
8,inc_1_primary_burner_status,17.02.2018 21:03:17,0,1,"43148877282,8125",2018-02-17 21:03:17
9,inc_1_secondary_burner_status,17.02.2018 21:03:17,-20,1,"43148877282,8125",2018-02-17 21:03:17

In [202]:
def Filtvar(df, col):
    """
    Picks up the rows with desired variables

    :input: Name of the dataframe and the desired variable in quotes ('').

    :return: pandas dataframe with only the desired variable in the VarName-column.
    In addition, returns the dimensions of the new filtered DataFrame.
    """

    df = df[df.VarName == col]
    n = df.shape[1]        # second element of "dimension" is the number of cols
    m = df.shape[0]        # first element of dimension is the number of rows
    
    print('sample size m=',m)
    print('feature length n=',n)

    return df, m, n

In [212]:
DWtest, m, n, = Filtvar(DWsource, 'inc_1_lower_feeding_gate_status')

sample size m= 125000
feature length n= 6

In [213]:
DWtest.head()

,VarName,TimeString,VarValue,Validity,Time_ms,DateTime
2,inc_1_lower_feeding_gate_status,17.02.2018 21:03:15,-10,1,"43148877259,4097",2018-02-17 21:03:15
6,inc_1_lower_feeding_gate_status,17.02.2018 21:03:16,-10,1,"43148877271,0995",2018-02-17 21:03:16
10,inc_1_lower_feeding_gate_status,17.02.2018 21:03:17,-10,1,"43148877282,8125",2018-02-17 21:03:17
14,inc_1_lower_feeding_gate_status,17.02.2018 21:03:18,-10,1,"43148877294,5023",2018-02-17 21:03:18
18,inc_1_lower_feeding_gate_status,17.02.2018 21:03:19,-10,1,"43148877306,2037",2018-02-17 21:03:19

In [211]:
DWtest.tail()

,VarName,TimeString,VarValue,Validity,Time_ms,DateTime
499982,inc_1_lower_feeding_gate_status,19.02.2018 08:07:41,-10,1,"43150338665,7755",2018-02-19 08:07:41
499986,inc_1_lower_feeding_gate_status,19.02.2018 08:07:42,-10,1,"43150338677,4653",2018-02-19 08:07:42
499990,inc_1_lower_feeding_gate_status,19.02.2018 08:07:43,-10,1,"43150338689,1667",2018-02-19 08:07:43
499994,inc_1_lower_feeding_gate_status,19.02.2018 08:07:44,-10,1,"43150338700,8565",2018-02-19 08:07:44
499998,inc_1_lower_feeding_gate_status,19.02.2018 08:07:45,-10,1,"43150338712,5463",2018-02-19 08:07:45

In [ ]:
DWtest.VarValue.value_counts()

In [ ]:
plt.plot(DWtest.DateTime, DWtest.VarValue)

In [ ]:
FWTank1Level = pd.read_csv('MS6/LEVEL_TANK_A0.csv', delimiter=';')

In [ ]:
FW.head()

In [ ]:
FWTank2Level = pd.read_csv('MunVene2/LEVEL_TANK_B0.csv', delimiter=';')

## Values for the FW tank 

- FW tank level as % filling of the full capacity e.g. 47 % 
- Haarslev FW pump status same as others (20 FWD, 15 BWD, 0 Stop, -5 Fault or overcurrent). 20: pump runs full speed at 60 Hz.
- 3-way valve is directing the FW-flow between 2 tanks

In [ ]:
FWTank1Level.head()

In [ ]:
FWTank2Level.head()

In [ ]:
FW1id = FWTank1Level.set_index('VarName')

In [ ]:
FW2id = FWTank2Level.set_index('VarName')

In [ ]:
FW1id.head()

In [ ]:
FW2id.head()

In [ ]:
FWT1 = FW1id.loc['FOODWASTE_TANK_A_LEVEL_TREND' , 'TimeString' : 'VarValue']

In [ ]:
FWT2 = FW2id.loc['FOODWASTE_TANK_B_LEVEL_TREND' , 'TimeString' : 'VarValue']

In [ ]:
FWSflow1 = FW1id.loc['HARSLEV_PUMP_1_1PM_1_STATUS', 'TimeString': 'VarValue']

In [ ]:
FWSflow2 = FW2id.loc['HARSLEV_PUMP_1_2PM_1_STATUS', 'TimeString': 'VarValue']

In [ ]:
print(FWT1.shape)

In [ ]:
FWT2.head()

In [ ]:
# FWT1['runTime'] = pd.date_range(start='2018-02-25 16:07:23', periods=67144, freq='S')
FWT1.dropna(inplace=True)

In [ ]:
# FWT1['meanLevel'] = FWT1['VarValue'].rolling(12).mean()
FWT1['levelDiff'] = FWT1['VarValue'].diff()
FWT1.dropna()

In [ ]:
# To remove the discharge from level measurement: Removes negative value < -1 and replaces the the values by zero
FWT1.levelDiff.where(FWT1.levelDiff > -2, 0, inplace=True)

In [ ]:
pd.to_datetime(FWT1.TimeString, format = '%d.%m.%Y %H:%M:%S')

In [176]:
# Converts time string values into datetime value and assigns the serie to new calTime-column
FWT1['calTime'] = pd.to_datetime(FWT1.TimeString, format = '%d.%m.%Y %H:%M:%S')

In [178]:
type(FWT1.calTime)

pandas.core.series.Series

In [ ]:
# Cumulative sum of level increase as percent value
FWT1['incrSum'] = FWT1.levelDiff.cumsum()

In [ ]:
# Cumulative sum of level increase as m3
FWT1['incrVsum'] = FWT1.incrSum * 5 / 100

In [ ]:
# Flow rate m3/h from 1 h earlier to that moment
FWT1['lhFlow'] = FWT1.incrVsum.diff(periods=720)*1000

In [ ]:
# To remove the discharge from level measurement: Removes negative value < -1 and replaces the the values by zero
FWT1['lmin] = FWT1.lminFlow.where(abs(FWT1.lminFlow) == 50, 0)

In [191]:
FWT1.tail(100)

,TimeString,VarValue,levelDiff,calTime,incrSum,incrVsum,lminFlow,m3hFlow,lhFlow
VarName,,,,,,,,,
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:11,33,0.0,2018-03-01 14:11:11,1244.0,62.20,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:16,33,0.0,2018-03-01 14:11:16,1244.0,62.20,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:21,33,0.0,2018-03-01 14:11:21,1244.0,62.20,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:26,33,0.0,2018-03-01 14:11:26,1244.0,62.20,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:31,33,0.0,2018-03-01 14:11:31,1244.0,62.20,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:36,33,0.0,2018-03-01 14:11:36,1244.0,62.20,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:41,33,0.0,2018-03-01 14:11:41,1244.0,62.20,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:46,33,0.0,2018-03-01 14:11:46,1244.0,62.20,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:51,33,0.0,2018-03-01 14:11:51,1244.0,62.20,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:11:56,34,1.0,2018-03-01 14:11:56,1245.0,62.25,1.20,1.20,1200.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:01,34,0.0,2018-03-01 14:12:01,1245.0,62.25,1.15,1.15,1150.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:06,34,0.0,2018-03-01 14:12:06,1245.0,62.25,1.20,1.20,1200.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:12,34,0.0,2018-03-01 14:12:12,1245.0,62.25,1.20,1.20,1200.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:17,34,0.0,2018-03-01 14:12:17,1245.0,62.25,1.20,1.20,1200.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:22,35,1.0,2018-03-01 14:12:22,1246.0,62.30,1.25,1.25,1250.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:27,35,0.0,2018-03-01 14:12:27,1246.0,62.30,1.25,1.25,1250.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:32,35,0.0,2018-03-01 14:12:32,1246.0,62.30,1.25,1.25,1250.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:37,35,0.0,2018-03-01 14:12:37,1246.0,62.30,1.20,1.20,1200.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:42,35,0.0,2018-03-01 14:12:42,1246.0,62.30,1.20,1.20,1200.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:47,36,1.0,2018-03-01 14:12:47,1247.0,62.35,1.25,1.25,1250.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:52,36,0.0,2018-03-01 14:12:52,1247.0,62.35,1.25,1.25,1250.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:12:57,36,0.0,2018-03-01 14:12:57,1247.0,62.35,1.25,1.25,1250.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:13:02,37,1.0,2018-03-01 14:13:02,1248.0,62.40,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:13:07,36,-1.0,2018-03-01 14:13:07,1247.0,62.35,1.25,1.25,1250.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:13:12,36,0.0,2018-03-01 14:13:12,1247.0,62.35,1.25,1.25,1250.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:13:17,36,0.0,2018-03-01 14:13:17,1247.0,62.35,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:13:22,37,1.0,2018-03-01 14:13:22,1248.0,62.40,1.35,1.35,1350.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:13:27,37,0.0,2018-03-01 14:13:27,1248.0,62.40,1.35,1.35,1350.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:13:32,37,0.0,2018-03-01 14:13:32,1248.0,62.40,1.35,1.35,1350.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:13:37,36,-1.0,2018-03-01 14:13:37,1247.0,62.35,1.30,1.30,1300.0
...,...,...,...,...,...,...,...,...,...
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:05,35,1.0,2018-03-01 14:17:05,1248.0,62.40,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:10,34,-1.0,2018-03-01 14:17:10,1247.0,62.35,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:15,35,1.0,2018-03-01 14:17:15,1248.0,62.40,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:20,34,-1.0,2018-03-01 14:17:20,1247.0,62.35,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:25,34,0.0,2018-03-01 14:17:25,1247.0,62.35,1.25,1.25,1250.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:30,36,2.0,2018-03-01 14:17:30,1249.0,62.45,1.35,1.35,1350.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:35,35,-1.0,2018-03-01 14:17:35,1248.0,62.40,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:40,35,0.0,2018-03-01 14:17:40,1248.0,62.40,1.35,1.35,1350.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:45,34,-1.0,2018-03-01 14:17:45,1247.0,62.35,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:50,34,0.0,2018-03-01 14:17:50,1247.0,62.35,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:17:55,35,1.0,2018-03-01 14:17:55,1248.0,62.40,1.35,1.35,1350.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:00,33,0.0,2018-03-01 14:18:00,1248.0,62.40,1.20,1.20,1200.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:05,33,0.0,2018-03-01 14:18:05,1248.0,62.40,1.20,1.20,1200.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:10,35,2.0,2018-03-01 14:18:10,1250.0,62.50,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:15,36,1.0,2018-03-01 14:18:15,1251.0,62.55,1.40,1.40,1400.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:20,35,-1.0,2018-03-01 14:18:20,1250.0,62.50,1.30,1.30,1300.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:25,35,0.0,2018-03-01 14:18:25,1250.0,62.50,1.35,1.35,1350.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:30,33,0.0,2018-03-01 14:18:30,1250.0,62.50,1.40,1.40,1400.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:35,34,1.0,2018-03-01 14:18:35,1251.0,62.55,1.50,1.50,1500.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:41,34,0.0,2018-03-01 14:18:41,1251.0,62.55,1.45,1.45,1450.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:46,34,0.0,2018-03-01 14:18:46,1251.0,62.55,1.50,1.50,1500.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:51,33,-1.0,2018-03-01 14:18:51,1250.0,62.50,1.40,1.40,1400.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:18:56,34,1.0,2018-03-01 14:18:56,1251.0,62.55,1.40,1.40,1400.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:19:01,35,1.0,2018-03-01 14:19:01,1252.0,62.60,1.50,1.50,1500.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:19:06,34,-1.0,2018-03-01 14:19:06,1251.0,62.55,1.45,1.45,1450.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:19:11,35,1.0,2018-03-01 14:19:11,1252.0,62.60,1.40,1.40,1400.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:19:16,34,-1.0,2018-03-01 14:19:16,1251.0,62.55,1.35,1.35,1350.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:19:21,35,1.0,2018-03-01 14:19:21,1252.0,62.60,1.45,1.45,1450.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:19:26,34,-1.0,2018-03-01 14:19:26,1251.0,62.55,1.45,1.45,1450.0
FOODWASTE_TANK_A_LEVEL_TREND,01.03.2018 14:19:31,33,-1.0,2018-03-01 14:19:31,1250.0,62.50,1.45,1.45,1450.0

In [ ]:
# Plot the volumetric cumulative sum against the time
plt.plot(FWT1.calTime, FWT1.incrVsum)

In [ ]:
plt.plot(FWT1.calTime, FWT1.lhFlow)

In [ ]:
FWT1.dtypes

In [ ]:
# Counts the numbers of status values for the pump. -5 == Fault status
FWSflow1.VarValue.value_counts()

In [ ]:
# Converts time string values into datetime value
FWSflow1['calTime'] = pd.to_datetime(FWSflow1.TimeString, format = '%d.%m.%Y %H:%M:%S')

In [ ]:
FWSflow1.dtypes

In [ ]:
# Removes fault-status (-5)
FWSflow1.VarValue.where(FWSflow1.VarValue > 0, 0, inplace=True)

In [ ]:
FWSflow1.VarValue.value_counts()

In [ ]:
# Code for if VarValue == 20 => flowrate = 0.1666 lmin

In [ ]:
FWSflow1.head()

In [ ]:
FWT2.head()

In [ ]:
FWT2.any(0)

In [ ]:
FWSflow2.head()

In [ ]:
x = FWT1.loc[:, 'TimeString']

In [ ]:
FWSflow1.plot()

In [ ]:
FWSflow2.plot()

## Division of the Food Waste flows 

The produced food waste is separated with a mesh in the tank into:

1. Solid food waste (FW)

2. Food waste water (FWW)

### Food Waste solids (FW)

FW is pumped with the Haarslew pump to the screen and further to the drier. As mentioned above, the variable value of 20 tells that the pump is producing with its capacity. The FW flow can be calculated directly from the data as: 

(flow capacity the pump (e.g. 2 kg / s)) / ( moment of first instance of VarValue 20 and moment of last instance of the VarValue 20)

### Food Waste water (FWW)

This data describes the flow of load in liquid form out of the waste system.

tank water pump 

- 20 Forward
- 15 Backward
- 0 Stop
- -5 Fault or overcurrent

No Hz info presumably 60 Hz

The FWW flow can be calculated directly from the data as: 

(flow capacity the pump (e.g. 20 kg / s)) / ( moment of first instance of VarValue 20 and moment of last instance of the VarValue 20)

The carbon can be considered as direct CO2- and nutrient emmision to the environment. All the carbon in the FW water are converted into CO2.

In [ ]:
FWW_flow = pd.read_csv('MunVene2/BORGEN_PUMP0.csv', delimiter=';')

In [ ]:
FWW_flow.head(2000)

In [ ]:
FWW_flow.tail()

## Values for the Biosludge tank:

- Biosludge mixing status: 0 = stop, 20 FWD, -5 Fail) 
- Biosludge tank level: as % filling of the full capacity e.g. 19 %

In [ ]:
BWTankLevel = pd.read_csv('MunVene2/LEVEL_BIOSLUDGETANK0.csv', delimiter=';')

In [ ]:
BWTankLevel.head()

In [ ]:
BWTankLevel.tail()

## Values for the Burners:

- All temperatures in the main and sec chambers as Celsius degrees

In [ ]:
Burner1 = pd.read_csv('MunVene2/BURNER_10.csv', delimiter=';')

In [ ]:
Burner1.head()

In [ ]:
Burner2 = pd.read_csv('MunVene2/BURNER_20.csv', delimiter=';')

In [ ]:
Burner2.head()

In [ ]:
Burner2.shape

In [ ]:
Dryer0 = pd.read_csv('MunVene2/DRYER0.csv', delimiter=';')

## Values for the Dryer:

- Dryer mixer motor current as %, e.g. 50 %
- Dryer temperature as Celcius degrees
- Dryer pressure as mbar
- Dryer filling weight as kgs

In [ ]:
Dryer0.shape

In [ ]:
Dryer0.head(20)

In [ ]:
FluegasTemp0 = pd.read_csv('MunVene2/FLUEGAS0.csv', delimiter=';')

## Values for the Flue gas:

- Flue gas temperature as Celcius degrees.
- Flue gas fan speed as Hz (or 1/10 Hz). Check!
- Flue gas opacity as 0 to 100 %

In [ ]:
FluegasTemp0.shape

In [ ]:
FluegasTemp0.head()

In [ ]:
FluegasFlow0 = pd.read_csv('MunVene2/ID_FAN0.csv', delimiter=';')

In [ ]:
FluegasFlow0.head()